In [122]:
import pandas as pd

In [123]:
house_data = pd.read_csv("data.csv")

In [124]:
house_data.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [125]:
house_data.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [126]:
house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [147]:
X = house_data.drop(columns=["price","street","date","country", "statezip"])
y = house_data["price"]

In [148]:
X.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,Shoreline
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,Seattle
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,Kent
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,Bellevue
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,Redmond

In [149]:
X = pd.get_dummies(X, columns=["city"], drop_first=True, dtype=int)

In [150]:
X

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,...,city_SeaTac,city_Seattle,city_Shoreline,city_Skykomish,city_Snoqualmie,city_Snoqualmie Pass,city_Tukwila,city_Vashon,city_Woodinville,city_Yarrow Point
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,...,0,0,1,0,0,0,0,0,0,0
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,...,0,1,0,0,0,0,0,0,0,0
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,...,0,0,0,0,0,0,0,0,0,0
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,...,0,0,0,0,0,0,0,0,0,0
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,...,0,1,0,0,0,0,0,0,0,0
4596,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,...,0,0,0,0,0,0,0,0,0,0
4597,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,...,0,0,0,0,0,0,0,0,0,0
4598,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,...,0,1,0,0,0,0,0,0,0,0
4599,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,...,0,0,0,0,0,0,0,0,0,0

In [157]:
# Always split BEFORE:

# scaling
# model training

# Train Test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [158]:
X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

In [159]:
# Scaling data 
from sklearn.preprocessing import StandardScaler

numeric_cols = ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
                'floors', 'view', 'condition', 'sqft_above', 'sqft_basement']

scaler = StandardScaler()

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [160]:
#Train Model

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [161]:
y_pred = model.predict(X_test)

In [162]:
y_test

0        544000.0
1             0.0
2       1712500.0
3        365000.0
4        275000.0
          ...
915      750000.0
916      230000.0
917    26590000.0
918      687000.0
919      289659.0
Name: price, Length: 920, dtype: float64

In [163]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

0.04146852385391753

In [111]:
X.shape

(4600, 12)

In [112]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(3680, 12) (3680,)
(920, 12) (920,)

In [ ]:
print(X_train.head())
print(y_train.head())

      bedrooms  bathrooms  sqft_living  sqft_lot    floors  waterfront  \
1898  0.670520   0.436902     0.660971  0.870054  0.910403           0
1370  0.670520   1.074918     1.652011  0.406802  0.910403           0
3038  0.670520   0.436902     0.702699 -0.097288  0.910403           0
2361  0.670520   2.031941     1.975402 -0.106289  0.910403           0
156  -0.430066  -0.201114    -0.142292 -0.213165  0.910403           0

          view  condition  sqft_above  sqft_basement  yr_built  yr_renovated
1898 -0.306194   0.808830    1.105179      -0.679582      1989             0
1370 -0.306194  -0.672013    2.211185      -0.679582      1991             0
3038 -0.306194  -0.672013    1.151748      -0.679582      1982             0
2361 -0.306194  -0.672013    2.572092      -0.679582      2006             0
156  -0.306194  -0.672013    0.208732      -0.679582      1916          1986
1898     685000.0
1370     857000.0
3038     675000.0
2361    1485000.0
156      561000.0
Name: price, dtype: float64